// user login/logout
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

// user registration/signup
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

// user activation
export const USER_ACTIVATE_REQUEST = "USER_ACTIVATE_REQUEST"
export const USER_ACTIVATE_SUCCESS = "USER_ACTIVATE_SUCCESS"
export const USER_ACTIVATE_FAIL = "USER_ACTIVATE_FAIL"

// user reset_password
export const USER_RESET_PASSWORD_REQUEST = "USER_RESET_PASSWORD_REQUEST"
export const USER_RESET_PASSWORD_SUCCESS = "USER_RESET_PASSWORD_SUCCESS"
export const USER_RESET_PASSWORD_FAIL = "USER_RESET_PASSWORD_FAIL"

// user reset_password_confirm
export const USER_RESET_PASSWORD_CONFIRM_REQUEST = "USER_RESET_PASSWORD_CONFIRM_REQUEST"
export const USER_RESET_PASSWORD_CONFIRM_SUCCESS = "USER_RESET_PASSWORD_CONFIRM_SUCCESS"
export const USER_RESET_PASSWORD_CONFIRM_FAIL = "USER_RESET_PASSWORD_CONFIRM_FAIL"

// home products(featured products, popular products recently viewed)
export const POST_INDEX_REQUEST = "POST_INDEX_REQUEST"
export const POST_INDEX_SUCCESS = "POST_INDEX_SUCCESS"
export const POST_INDEX_FAIL = "POST_INDEX_FAIL"


export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const LIST_AGENTS_REQUEST = "LIST_AGENTS_REQUEST";
export const LIST_AGENTS_SUCCESS = "LIST_AGENTS_SUCCESS";
export const LIST_AGENTS_FAIL = "LIST_AGENTS_FAIL";

export const LIST_TOP_AGENTS_REQUEST = "LIST_TOP_AGENTS_REQUEST";
export const LIST_TOP_AGENTS_SUCCESS = "LIST_TOP_AGENTS_SUCCESS";
export const LIST_TOP_AGENTS_FAIL = "LIST_TOP_AGENTS_FAIL";

export const LIST_ALL_USERS_PROFILE_REQUEST = "LIST_ALL_USERS_PROFILE_REQUEST"
export const LIST_ALL_USERS_PROFILE_SUCCESS = "LIST_ALL_USERS_PROFILE_SUCCESS"
export const LIST_ALL_USERS_PROFILE_FAIL = "LIST_ALL_USERS_PROFILE_FAIL"